In [21]:
#multiple linear regression
from pymongo import MongoClient
import requests
import numpy as np
import pandas as pd
import urllib
client = MongoClient('mongodb+srv://Yuqing:password@cluster0.xx7g0.mongodb.net/myFirstDatabase?retryWrites=true&w=majority')
mydb = client["Steam"]



In [23]:
def get_request(url, parameters=None):
    try:
        #Convert dictionary format to url parameter mode
        params = urllib.parse.urlencode(parameters)
        url = url +'/?' + params
        response = requests.get(url=url)
    except SSLError as s:
        print('SSL Error:', s)
        
        for i in range(5, 0, -1):
            print('\rWaiting... ({})'.format(i), end='')
            time.sleep(1)
        print('\rRetrying.' + ' '*10)
    except ConnectionError:
        time.sleep(10)
        # recusively try again
        return get_request(url, parameters)
    
    if response:
        return response.json()
    else:
        # response is none usually means too many requests. Wait and try again 
        print('No response, waiting 10 seconds...')
        time.sleep(10)
        print('Retrying.')
        return get_request(url, parameters)

In [133]:
import numpy as np
LR_data = pd.DataFrame(list(mydb.LR.find()))
LR_ = LR_data.drop(columns=['_id','steamid'])
re = LR_[['State']]
print(re)
LR = LR_.to_numpy()
LR = np.delete(LR, 0, axis=1)                       
print(LR)


    State
0        
1     QLD
2        
3        
4     NSW
..    ...
902   VIC
903      
904      
905   QLD
906      

[907 rows x 1 columns]
[[253 172070 0.702791223380439 1 535]
 [0 0 0.0 0 0]
 [0 0 0.0 0 0]
 ...
 [228 711540 0.730555685668272 5 2208]
 [170 828039 0.7059210191985538 1 116]
 [0 0 0.0 0 0]]


In [134]:
#null -0; NSW-1; VIC-2; QLD-3; SA-4; WA-5; TAS-6; ACT-7; NT-8
for i, row in re.iterrows():
    if row['State'] == '':
        re.at[i,'State']  = 0
    elif row['State'] == 'NSW':
        re.at[i,'State']  = 1
    elif row['State'] == 'VIC':
        re.at[i,'State']  = 2
    elif row['State'] == 'QLD':
        re.at[i,'State']  = 3
    elif row['State'] == 'SA':
        re.at[i,'State'] = 4
    elif row['State'] == 'WA':
        re.at[i,'State']  = 5
    elif row['State'] == 'TAS':
        re.at[i,'State']  = 6
    elif row['State'] == 'ACT':
        re.at[i,'State']  = 7
    elif row['State'] == 'NT':
        re.at[i,'State']  = 8
re = re.to_numpy()


In [135]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    LR, re, test_size=0.33, random_state=42)

In [136]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
r = regr.fit(X_train, y_train)

In [155]:
predicted = r.predict(X_test)
#round(predicted)
for i in range(len(predicted)):
    #print(i[0])
    num = 0
    
    if round(predicted[i][0]) == y_test[i][0]:
        num = num +1 
leng =  len(predicted)
accu = num/leng